// <autogenerated />
namespace PhotoBuddy.Screens
{
    partial class AlbumViewUserControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            stopRefreshToken.Cancel();
            if (this.stopAddToken != null)
            {
                this.stopAddToken.Cancel();
            }
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.AlbumPanel = new System.Windows.Forms.TableLayoutPanel();
            this.HeaderPanel = new System.Windows.Forms.Panel();
            this.albumSizeLabel = new System.Windows.Forms.Label();
            this.AlbumHeaderPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.AlbumNameLabel = new System.Windows.Forms.Label();
            this.FooterPanel = new System.Windows.Forms.Panel();
            this.AddPhotosButton = new System.Windows.Forms.Button();
            this.BackButton = new System.Windows.Forms.Button();
            this.PhotosFlowPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.ContentPanel = new System.Windows.Forms.Panel();
            this.AddPhotosFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.AlbumPanel.SuspendLayout();
            this.HeaderPanel.SuspendLayout();
            this.AlbumHeaderPanel.SuspendLayout();
            this.FooterPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // AlbumPanel
            // 
            this.AlbumPanel.BackColor = System.Drawing.Color.Transparent;
            this.AlbumPanel.ColumnCount = 1;
            this.AlbumPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.AlbumPanel.Controls.Add(this.HeaderPanel, 0, 0);
            this.AlbumPanel.Controls.Add(this.FooterPanel, 0, 3);
            this.AlbumPanel.Controls.Add(this.PhotosFlowPanel, 0, 2);
            this.AlbumPanel.Controls.Add(this.ContentPanel, 0, 1);
            this.AlbumPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.AlbumPanel.Location = new System.Drawing.Point(0, 0);
            this.AlbumPanel.Margin = new System.Windows.Forms.Padding(2);
            this.AlbumPanel.Name = "AlbumPanel";
            this.AlbumPanel.RowCount = 4;
            this.AlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 37F));
            this.AlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 1F));
            this.AlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.AlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.AlbumPanel.Size = new System.Drawing.Size(375, 325);
            this.AlbumPanel.TabIndex = 2;
            // 
            // HeaderPanel
            // 
            this.HeaderPanel.Controls.Add(this.albumSizeLabel);
            this.HeaderPanel.Controls.Add(this.AlbumHeaderPanel);
            this.HeaderPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.HeaderPanel.Location = new System.Drawing.Point(0, 0);
            this.HeaderPanel.Margin = new System.Windows.Forms.Padding(0);
            this.HeaderPanel.Name = "HeaderPanel";
            this.HeaderPanel.Size = new System.Drawing.Size(375, 37);
            this.HeaderPanel.TabIndex = 0;
            // 
            // albumSizeLabel
            // 
            this.albumSizeLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.albumSizeLabel.AutoSize = true;
            this.albumSizeLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.albumSizeLabel.ForeColor = System.Drawing.Color.Black;
            this.albumSizeLabel.Location = new System.Drawing.Point(289, 17);
            this.albumSizeLabel.Margin = new System.Windows.Forms.Padding(2, 0, 30, 0);
            this.albumSizeLabel.Name = "albumSizeLabel";
            this.albumSizeLabel.Size = new System.Drawing.Size(63, 17);
            this.albumSizeLabel.TabIndex = 4;
            this.albumSizeLabel.Text = "0 photos";
            // 
            // AlbumHeaderPanel
            // 
            this.AlbumHeaderPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.AlbumHeaderPanel.AutoSize = true;
            this.AlbumHeaderPanel.Controls.Add(this.AlbumNameLabel);
            this.AlbumHeaderPanel.Location = new System.Drawing.Point(10, -6);
            this.AlbumHeaderPanel.Margin = new System.Windows.Forms.Padding(0);
            this.AlbumHeaderPanel.Name = "AlbumHeaderPanel";
            this.AlbumHeaderPanel.Size = new System.Drawing.Size(239, 41);
            this.AlbumHeaderPanel.TabIndex = 3;
            this.AlbumHeaderPanel.WrapContents = false;
            // 
            // AlbumNameLabel
            // 
            this.AlbumNameLabel.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.AlbumNameLabel.AutoSize = true;
            this.AlbumNameLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AlbumNameLabel.ForeColor = System.Drawing.Color.Black;
            this.AlbumNameLabel.Location = new System.Drawing.Point(0, 10);
            this.AlbumNameLabel.Margin = new System.Windows.Forms.Padding(0, 10, 0, 0);
            this.AlbumNameLabel.MaximumSize = new System.Drawing.Size(400, 31);
            this.AlbumNameLabel.Name = "AlbumNameLabel";
            this.AlbumNameLabel.Size = new System.Drawing.Size(161, 31);
            this.AlbumNameLabel.TabIndex = 2;
            this.AlbumNameLabel.Text = "album name";
            this.AlbumNameLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // FooterPanel
            // 
            this.FooterPanel.BackColor = System.Drawing.Color.WhiteSmoke;
            this.FooterPanel.Controls.Add(this.AddPhotosButton);
            this.FooterPanel.Controls.Add(this.BackButton);
            this.FooterPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.FooterPanel.Location = new System.Drawing.Point(0, 289);
            this.FooterPanel.Margin = new System.Windows.Forms.Padding(0);
            this.FooterPanel.Name = "FooterPanel";
            this.FooterPanel.Size = new System.Drawing.Size(375, 36);
            this.FooterPanel.TabIndex = 1;
            // 
            // AddPhotosButton
            // 
            this.AddPhotosButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.AddPhotosButton.AutoSize = true;
            this.AddPhotosButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.AddPhotosButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.AddPhotosButton.FlatAppearance.BorderSize = 0;
            this.AddPhotosButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.AddPhotosButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.AddPhotosButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AddPhotosButton.ForeColor = System.Drawing.Color.White;
            this.AddPhotosButton.Location = new System.Drawing.Point(262, 1);
            this.AddPhotosButton.Margin = new System.Windows.Forms.Padding(0, 0, 10, 0);
            this.AddPhotosButton.Name = "AddPhotosButton";
            this.AddPhotosButton.Size = new System.Drawing.Size(102, 30);
            this.AddPhotosButton.TabIndex = 0;
            this.AddPhotosButton.Text = "Add Photos";
            this.AddPhotosButton.UseVisualStyleBackColor = false;
            this.AddPhotosButton.Click += new System.EventHandler(this.HandleAddPhotosButtonClick);
            this.AddPhotosButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.AddPhotosButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // BackButton
            // 
            this.BackButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BackButton.AutoSize = true;
            this.BackButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.BackButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.BackButton.FlatAppearance.BorderSize = 0;
            this.BackButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.BackButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.BackButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BackButton.ForeColor = System.Drawing.Color.White;
            this.BackButton.Location = new System.Drawing.Point(200, 1);
            this.BackButton.Margin = new System.Windows.Forms.Padding(0, 0, 8, 0);
            this.BackButton.Name = "BackButton";
            this.BackButton.Size = new System.Drawing.Size(55, 30);
            this.BackButton.TabIndex = 1;
            this.BackButton.Text = "Back";
            this.BackButton.UseVisualStyleBackColor = false;
            this.BackButton.Click += new System.EventHandler(this.HandleBackButtonClick);
            this.BackButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.BackButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // PhotosFlowPanel
            // 
            this.PhotosFlowPanel.AutoScroll = true;
            this.PhotosFlowPanel.BackColor = System.Drawing.Color.White;
            this.PhotosFlowPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PhotosFlowPanel.Location = new System.Drawing.Point(10, 41);
            this.PhotosFlowPanel.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
            this.PhotosFlowPanel.Name = "PhotosFlowPanel";
            this.PhotosFlowPanel.Size = new System.Drawing.Size(355, 245);
            this.PhotosFlowPanel.TabIndex = 2;
            this.PhotosFlowPanel.MouseClick += new System.Windows.Forms.MouseEventHandler(this.HandlePhotosFlowPanelMouseClick);
            this.PhotosFlowPanel.MouseEnter += new System.EventHandler(this.HandlePhotosFlowPanelMouseEnter);
            // 
            // ContentPanel
            // 
            this.ContentPanel.BackColor = System.Drawing.Color.Black;
            this.ContentPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ContentPanel.Location = new System.Drawing.Point(10, 37);
            this.ContentPanel.Margin = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.ContentPanel.Name = "ContentPanel";
            this.ContentPanel.Size = new System.Drawing.Size(355, 1);
            this.ContentPanel.TabIndex = 3;
            // 
            // AddPhotosFileDialog
            // 
            this.AddPhotosFileDialog.Filter = "(*.png;*.bmp;*.jpg;*.gif)|*.png;*.bmp;*.jpg;*.gif|All files (*.*)|*.* ";
            this.AddPhotosFileDialog.Multiselect = true;
            // 
            // AlbumViewUserControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this.AlbumPanel);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "AlbumViewUserControl";
            this.Size = new System.Drawing.Size(375, 325);
            this.AlbumPanel.ResumeLayout(false);
            this.HeaderPanel.ResumeLayout(false);
            this.HeaderPanel.PerformLayout();
            this.AlbumHeaderPanel.ResumeLayout(false);
            this.AlbumHeaderPanel.PerformLayout();
            this.FooterPanel.ResumeLayout(false);
            this.FooterPanel.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel AlbumPanel;
        private System.Windows.Forms.Panel HeaderPanel;
        private System.Windows.Forms.Panel FooterPanel;
        private System.Windows.Forms.Button AddPhotosButton;
        private System.Windows.Forms.Button BackButton;
        private System.Windows.Forms.Label AlbumNameLabel;
        private System.Windows.Forms.FlowLayoutPanel PhotosFlowPanel;
        private System.Windows.Forms.FlowLayoutPanel AlbumHeaderPanel;
        private System.Windows.Forms.Panel ContentPanel;
        private System.Windows.Forms.OpenFileDialog AddPhotosFileDialog;
        private System.Windows.Forms.Label albumSizeLabel;
    }
}
