// <autogenerated />
namespace PhotoBuddy.Screens
{
    partial class AlbumViewUserControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            stopRefreshToken.Cancel();
            if (this.stopAddToken != null)
            {
                this.stopAddToken.Cancel();
            }
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.AlbumPanel = new System.Windows.Forms.TableLayoutPanel();
            this.headerPanel = new System.Windows.Forms.Panel();
            this.albumSizeLabel = new System.Windows.Forms.Label();
            this.AlbumHeaderPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.albumNameLabel = new System.Windows.Forms.Label();
            this.footerPanel = new System.Windows.Forms.Panel();
            this.addPhotosButton = new System.Windows.Forms.Button();
            this.backButton = new System.Windows.Forms.Button();
            this.photosFlowPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.contentPanel = new System.Windows.Forms.Panel();
            this.addPhotosFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.AlbumPanel.SuspendLayout();
            this.headerPanel.SuspendLayout();
            this.AlbumHeaderPanel.SuspendLayout();
            this.footerPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // AlbumPanel
            // 
            this.AlbumPanel.BackColor = System.Drawing.Color.Transparent;
            this.AlbumPanel.ColumnCount = 1;
            this.AlbumPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.AlbumPanel.Controls.Add(this.headerPanel, 0, 0);
            this.AlbumPanel.Controls.Add(this.footerPanel, 0, 3);
            this.AlbumPanel.Controls.Add(this.photosFlowPanel, 0, 2);
            this.AlbumPanel.Controls.Add(this.contentPanel, 0, 1);
            this.AlbumPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.AlbumPanel.Location = new System.Drawing.Point(0, 0);
            this.AlbumPanel.Margin = new System.Windows.Forms.Padding(2);
            this.AlbumPanel.Name = "AlbumPanel";
            this.AlbumPanel.RowCount = 4;
            this.AlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 37F));
            this.AlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 1F));
            this.AlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.AlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.AlbumPanel.Size = new System.Drawing.Size(375, 325);
            this.AlbumPanel.TabIndex = 2;
            // 
            // headerPanel
            // 
            this.headerPanel.Controls.Add(this.albumSizeLabel);
            this.headerPanel.Controls.Add(this.AlbumHeaderPanel);
            this.headerPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.headerPanel.Location = new System.Drawing.Point(0, 0);
            this.headerPanel.Margin = new System.Windows.Forms.Padding(0);
            this.headerPanel.Name = "headerPanel";
            this.headerPanel.Size = new System.Drawing.Size(375, 37);
            this.headerPanel.TabIndex = 0;
            // 
            // albumSizeLabel
            // 
            this.albumSizeLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.albumSizeLabel.AutoSize = true;
            this.albumSizeLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.albumSizeLabel.ForeColor = System.Drawing.Color.Black;
            this.albumSizeLabel.Location = new System.Drawing.Point(289, 17);
            this.albumSizeLabel.Margin = new System.Windows.Forms.Padding(2, 0, 30, 0);
            this.albumSizeLabel.Name = "albumSizeLabel";
            this.albumSizeLabel.Size = new System.Drawing.Size(63, 17);
            this.albumSizeLabel.TabIndex = 4;
            this.albumSizeLabel.Text = "0 photos";
            // 
            // AlbumHeaderPanel
            // 
            this.AlbumHeaderPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.AlbumHeaderPanel.AutoSize = true;
            this.AlbumHeaderPanel.Controls.Add(this.albumNameLabel);
            this.AlbumHeaderPanel.Location = new System.Drawing.Point(10, -6);
            this.AlbumHeaderPanel.Margin = new System.Windows.Forms.Padding(0);
            this.AlbumHeaderPanel.Name = "AlbumHeaderPanel";
            this.AlbumHeaderPanel.Size = new System.Drawing.Size(239, 41);
            this.AlbumHeaderPanel.TabIndex = 3;
            this.AlbumHeaderPanel.WrapContents = false;
            // 
            // albumNameLabel
            // 
            this.albumNameLabel.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.albumNameLabel.AutoSize = true;
            this.albumNameLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.albumNameLabel.ForeColor = System.Drawing.Color.Black;
            this.albumNameLabel.Location = new System.Drawing.Point(0, 10);
            this.albumNameLabel.Margin = new System.Windows.Forms.Padding(0, 10, 0, 0);
            this.albumNameLabel.MaximumSize = new System.Drawing.Size(400, 31);
            this.albumNameLabel.Name = "albumNameLabel";
            this.albumNameLabel.Size = new System.Drawing.Size(161, 31);
            this.albumNameLabel.TabIndex = 2;
            this.albumNameLabel.Text = "album name";
            this.albumNameLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // footerPanel
            // 
            this.footerPanel.BackColor = System.Drawing.Color.WhiteSmoke;
            this.footerPanel.Controls.Add(this.addPhotosButton);
            this.footerPanel.Controls.Add(this.backButton);
            this.footerPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.footerPanel.Location = new System.Drawing.Point(0, 289);
            this.footerPanel.Margin = new System.Windows.Forms.Padding(0);
            this.footerPanel.Name = "footerPanel";
            this.footerPanel.Size = new System.Drawing.Size(375, 36);
            this.footerPanel.TabIndex = 1;
            // 
            // addPhotosButton
            // 
            this.addPhotosButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.addPhotosButton.AutoSize = true;
            this.addPhotosButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.addPhotosButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.addPhotosButton.FlatAppearance.BorderSize = 0;
            this.addPhotosButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.addPhotosButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.addPhotosButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addPhotosButton.ForeColor = System.Drawing.Color.White;
            this.addPhotosButton.Location = new System.Drawing.Point(262, 1);
            this.addPhotosButton.Margin = new System.Windows.Forms.Padding(0, 0, 10, 0);
            this.addPhotosButton.Name = "addPhotosButton";
            this.addPhotosButton.Size = new System.Drawing.Size(102, 30);
            this.addPhotosButton.TabIndex = 0;
            this.addPhotosButton.Text = "Add Photos";
            this.addPhotosButton.UseVisualStyleBackColor = false;
            this.addPhotosButton.Click += new System.EventHandler(this.HandleAddPhotosButtonClick);
            this.addPhotosButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.addPhotosButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // backButton
            // 
            this.backButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.backButton.AutoSize = true;
            this.backButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.backButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.backButton.FlatAppearance.BorderSize = 0;
            this.backButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.backButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.backButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.backButton.ForeColor = System.Drawing.Color.White;
            this.backButton.Location = new System.Drawing.Point(200, 1);
            this.backButton.Margin = new System.Windows.Forms.Padding(0, 0, 8, 0);
            this.backButton.Name = "backButton";
            this.backButton.Size = new System.Drawing.Size(55, 30);
            this.backButton.TabIndex = 1;
            this.backButton.Text = "Back";
            this.backButton.UseVisualStyleBackColor = false;
            this.backButton.Click += new System.EventHandler(this.HandleBackButtonClick);
            this.backButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.backButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // photosFlowPanel
            // 
            this.photosFlowPanel.AutoScroll = true;
            this.photosFlowPanel.BackColor = System.Drawing.Color.White;
            this.photosFlowPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.photosFlowPanel.Location = new System.Drawing.Point(10, 41);
            this.photosFlowPanel.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
            this.photosFlowPanel.Name = "photosFlowPanel";
            this.photosFlowPanel.Size = new System.Drawing.Size(355, 245);
            this.photosFlowPanel.TabIndex = 2;
            this.photosFlowPanel.MouseClick += new System.Windows.Forms.MouseEventHandler(this.HandlePhotosFlowPanelMouseClick);
            this.photosFlowPanel.MouseEnter += new System.EventHandler(this.HandlePhotosFlowPanelMouseEnter);
            // 
            // contentPanel
            // 
            this.contentPanel.BackColor = System.Drawing.Color.Black;
            this.contentPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.contentPanel.Location = new System.Drawing.Point(10, 37);
            this.contentPanel.Margin = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.contentPanel.Name = "contentPanel";
            this.contentPanel.Size = new System.Drawing.Size(355, 1);
            this.contentPanel.TabIndex = 3;
            // 
            // addPhotosFileDialog
            // 
            this.addPhotosFileDialog.Filter = "(*.png;*.bmp;*.jpg;*.gif)|*.png;*.bmp;*.jpg;*.gif|All files (*.*)|*.* ";
            this.addPhotosFileDialog.Multiselect = true;
            // 
            // AlbumViewUserControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this.AlbumPanel);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "AlbumViewUserControl";
            this.Size = new System.Drawing.Size(375, 325);
            this.AlbumPanel.ResumeLayout(false);
            this.headerPanel.ResumeLayout(false);
            this.headerPanel.PerformLayout();
            this.AlbumHeaderPanel.ResumeLayout(false);
            this.AlbumHeaderPanel.PerformLayout();
            this.footerPanel.ResumeLayout(false);
            this.footerPanel.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel AlbumPanel;
        private System.Windows.Forms.Panel headerPanel;
        private System.Windows.Forms.Panel footerPanel;
        private System.Windows.Forms.Button addPhotosButton;
        private System.Windows.Forms.Button backButton;
        private System.Windows.Forms.Label albumNameLabel;
        private System.Windows.Forms.FlowLayoutPanel photosFlowPanel;
        private System.Windows.Forms.FlowLayoutPanel AlbumHeaderPanel;
        private System.Windows.Forms.Panel contentPanel;
        private System.Windows.Forms.OpenFileDialog addPhotosFileDialog;
        private System.Windows.Forms.Label albumSizeLabel;
    }
}
