// <autogenerated />
namespace PhotoBuddy.Screens
{
    partial class CreateAlbumUserControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.CreateAlbumPanel = new System.Windows.Forms.TableLayoutPanel();
            this.CrateAlbumTextPanel = new System.Windows.Forms.Panel();
            this.cancelButton = new System.Windows.Forms.Button();
            this.albumNameTextBox = new System.Windows.Forms.TextBox();
            this.continueButton = new System.Windows.Forms.Button();
            this.createAlbumLabel = new System.Windows.Forms.Label();
            this.createHeaderLabel = new System.Windows.Forms.Label();
            this.dividerPanel = new System.Windows.Forms.Panel();
            this.CreateAlbumPanel.SuspendLayout();
            this.CrateAlbumTextPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // CreateAlbumPanel
            // 
            this.CreateAlbumPanel.ColumnCount = 3;
            this.CreateAlbumPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.CreateAlbumPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 345F));
            this.CreateAlbumPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.CreateAlbumPanel.Controls.Add(this.CrateAlbumTextPanel, 1, 2);
            this.CreateAlbumPanel.Controls.Add(this.createHeaderLabel, 0, 0);
            this.CreateAlbumPanel.Controls.Add(this.dividerPanel, 0, 1);
            this.CreateAlbumPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CreateAlbumPanel.Location = new System.Drawing.Point(0, 0);
            this.CreateAlbumPanel.Name = "CreateAlbumPanel";
            this.CreateAlbumPanel.RowCount = 6;
            this.CreateAlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 37F));
            this.CreateAlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 1F));
            this.CreateAlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.CreateAlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 130F));
            this.CreateAlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 49F));
            this.CreateAlbumPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.CreateAlbumPanel.Size = new System.Drawing.Size(375, 325);
            this.CreateAlbumPanel.TabIndex = 1;
            // 
            // CrateAlbumTextPanel
            // 
            this.CrateAlbumTextPanel.BackColor = System.Drawing.Color.WhiteSmoke;
            this.CrateAlbumTextPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.CrateAlbumTextPanel.Controls.Add(this.cancelButton);
            this.CrateAlbumTextPanel.Controls.Add(this.albumNameTextBox);
            this.CrateAlbumTextPanel.Controls.Add(this.continueButton);
            this.CrateAlbumTextPanel.Controls.Add(this.createAlbumLabel);
            this.CrateAlbumTextPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CrateAlbumTextPanel.Location = new System.Drawing.Point(15, 48);
            this.CrateAlbumTextPanel.Margin = new System.Windows.Forms.Padding(0, 10, 0, 0);
            this.CrateAlbumTextPanel.Name = "CrateAlbumTextPanel";
            this.CreateAlbumPanel.SetRowSpan(this.CrateAlbumTextPanel, 3);
            this.CrateAlbumTextPanel.Size = new System.Drawing.Size(345, 219);
            this.CrateAlbumTextPanel.TabIndex = 4;
            // 
            // cancelButton
            // 
            this.cancelButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.cancelButton.AutoSize = true;
            this.cancelButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.cancelButton.BackColor = System.Drawing.Color.Gainsboro;
            this.cancelButton.FlatAppearance.BorderSize = 0;
            this.cancelButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.cancelButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cancelButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cancelButton.ForeColor = System.Drawing.Color.Black;
            this.cancelButton.Location = new System.Drawing.Point(265, 179);
            this.cancelButton.Margin = new System.Windows.Forms.Padding(0, 0, 10, 0);
            this.cancelButton.Name = "cancelButton";
            this.cancelButton.Size = new System.Drawing.Size(68, 30);
            this.cancelButton.TabIndex = 4;
            this.cancelButton.Text = "Cancel";
            this.cancelButton.UseVisualStyleBackColor = false;
            this.cancelButton.Click += new System.EventHandler(this.HandleCancelButtonClick);
            // 
            // albumNameTextBox
            // 
            this.albumNameTextBox.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.albumNameTextBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.albumNameTextBox.Location = new System.Drawing.Point(9, 55);
            this.albumNameTextBox.Margin = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.albumNameTextBox.Name = "albumNameTextBox";
            this.albumNameTextBox.Size = new System.Drawing.Size(325, 35);
            this.albumNameTextBox.TabIndex = 0;
            this.albumNameTextBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.HandleAlbumNameTextBoxKeyDown);
            // 
            // continueButton
            // 
            this.continueButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.continueButton.AutoSize = true;
            this.continueButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.continueButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.continueButton.FlatAppearance.BorderSize = 0;
            this.continueButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.continueButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.continueButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.continueButton.ForeColor = System.Drawing.Color.White;
            this.continueButton.Location = new System.Drawing.Point(216, 179);
            this.continueButton.Margin = new System.Windows.Forms.Padding(0, 0, 8, 0);
            this.continueButton.Name = "continueButton";
            this.continueButton.Size = new System.Drawing.Size(41, 30);
            this.continueButton.TabIndex = 3;
            this.continueButton.Text = "OK";
            this.continueButton.UseVisualStyleBackColor = false;
            this.continueButton.Click += new System.EventHandler(this.HandleContinueButtonClick);
            this.continueButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.continueButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // createAlbumLabel
            // 
            this.createAlbumLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.createAlbumLabel.AutoSize = true;
            this.createAlbumLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.createAlbumLabel.Location = new System.Drawing.Point(39, 10);
            this.createAlbumLabel.Name = "createAlbumLabel";
            this.createAlbumLabel.Size = new System.Drawing.Size(266, 17);
            this.createAlbumLabel.TabIndex = 5;
            this.createAlbumLabel.Text = "Please enter the name of the new album:";
            this.createAlbumLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // createHeaderLabel
            // 
            this.createHeaderLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.createHeaderLabel.AutoSize = true;
            this.CreateAlbumPanel.SetColumnSpan(this.createHeaderLabel, 3);
            this.createHeaderLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.createHeaderLabel.Location = new System.Drawing.Point(10, 6);
            this.createHeaderLabel.Margin = new System.Windows.Forms.Padding(10, 0, 2, 0);
            this.createHeaderLabel.Name = "createHeaderLabel";
            this.createHeaderLabel.Size = new System.Drawing.Size(363, 31);
            this.createHeaderLabel.TabIndex = 6;
            this.createHeaderLabel.Text = "label1";
            this.createHeaderLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // dividerPanel
            // 
            this.dividerPanel.BackColor = System.Drawing.Color.Black;
            this.CreateAlbumPanel.SetColumnSpan(this.dividerPanel, 3);
            this.dividerPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dividerPanel.Location = new System.Drawing.Point(10, 37);
            this.dividerPanel.Margin = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.dividerPanel.Name = "dividerPanel";
            this.dividerPanel.Size = new System.Drawing.Size(355, 1);
            this.dividerPanel.TabIndex = 7;
            // 
            // CreateAlbumUserControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this.CreateAlbumPanel);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "CreateAlbumUserControl";
            this.Size = new System.Drawing.Size(375, 325);
            this.CreateAlbumPanel.ResumeLayout(false);
            this.CreateAlbumPanel.PerformLayout();
            this.CrateAlbumTextPanel.ResumeLayout(false);
            this.CrateAlbumTextPanel.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel CreateAlbumPanel;
        private System.Windows.Forms.Panel CrateAlbumTextPanel;
        private System.Windows.Forms.Button cancelButton;
        private System.Windows.Forms.Button continueButton;
        private System.Windows.Forms.TextBox albumNameTextBox;
        private System.Windows.Forms.Label createAlbumLabel;
        private System.Windows.Forms.Label createHeaderLabel;
        private System.Windows.Forms.Panel dividerPanel;
    }
}
