// <autogenerated />
namespace PhotoBuddy.Screens
{
    partial class HomeScreenUserControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.HomeScreenPanel = new System.Windows.Forms.TableLayoutPanel();
            this.HeadingPanel = new System.Windows.Forms.Panel();
            this.AlbumsLabel = new System.Windows.Forms.Label();
            this.HomeScreenActionPanel = new System.Windows.Forms.Panel();
            this.CreateButton = new System.Windows.Forms.Button();
            this.ExitButton = new System.Windows.Forms.Button();
            this.albumsFlowPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.DividerPanel = new System.Windows.Forms.Panel();
            this.HomeScreenPanel.SuspendLayout();
            this.HeadingPanel.SuspendLayout();
            this.HomeScreenActionPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // HomeScreenPanel
            // 
            this.HomeScreenPanel.BackColor = System.Drawing.Color.Transparent;
            this.HomeScreenPanel.ColumnCount = 1;
            this.HomeScreenPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.HomeScreenPanel.Controls.Add(this.HeadingPanel, 0, 0);
            this.HomeScreenPanel.Controls.Add(this.HomeScreenActionPanel, 0, 3);
            this.HomeScreenPanel.Controls.Add(this.albumsFlowPanel, 0, 2);
            this.HomeScreenPanel.Controls.Add(this.DividerPanel, 0, 1);
            this.HomeScreenPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.HomeScreenPanel.Location = new System.Drawing.Point(0, 0);
            this.HomeScreenPanel.Margin = new System.Windows.Forms.Padding(2);
            this.HomeScreenPanel.Name = "HomeScreenPanel";
            this.HomeScreenPanel.RowCount = 4;
            this.HomeScreenPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.HomeScreenPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 1F));
            this.HomeScreenPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.HomeScreenPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.HomeScreenPanel.Size = new System.Drawing.Size(300, 244);
            this.HomeScreenPanel.TabIndex = 1;
            // 
            // HeadingPanel
            // 
            this.HeadingPanel.Controls.Add(this.AlbumsLabel);
            this.HeadingPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.HeadingPanel.Location = new System.Drawing.Point(0, 0);
            this.HeadingPanel.Margin = new System.Windows.Forms.Padding(0);
            this.HeadingPanel.Name = "HeadingPanel";
            this.HeadingPanel.Size = new System.Drawing.Size(300, 35);
            this.HeadingPanel.TabIndex = 0;
            // 
            // AlbumsLabel
            // 
            this.AlbumsLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.AlbumsLabel.AutoSize = true;
            this.AlbumsLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AlbumsLabel.ForeColor = System.Drawing.Color.Black;
            this.AlbumsLabel.Location = new System.Drawing.Point(10, 4);
            this.AlbumsLabel.Margin = new System.Windows.Forms.Padding(10, 0, 2, 0);
            this.AlbumsLabel.Name = "AlbumsLabel";
            this.AlbumsLabel.Size = new System.Drawing.Size(104, 31);
            this.AlbumsLabel.TabIndex = 0;
            this.AlbumsLabel.Text = "Albums";
            this.AlbumsLabel.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            // 
            // HomeScreenActionPanel
            // 
            this.HomeScreenActionPanel.BackColor = System.Drawing.Color.WhiteSmoke;
            this.HomeScreenActionPanel.Controls.Add(this.CreateButton);
            this.HomeScreenActionPanel.Controls.Add(this.ExitButton);
            this.HomeScreenActionPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.HomeScreenActionPanel.Location = new System.Drawing.Point(0, 208);
            this.HomeScreenActionPanel.Margin = new System.Windows.Forms.Padding(0);
            this.HomeScreenActionPanel.Name = "HomeScreenActionPanel";
            this.HomeScreenActionPanel.Size = new System.Drawing.Size(300, 36);
            this.HomeScreenActionPanel.TabIndex = 1;
            // 
            // CreateButton
            // 
            this.CreateButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.CreateButton.AutoSize = true;
            this.CreateButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.CreateButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.CreateButton.FlatAppearance.BorderSize = 0;
            this.CreateButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.CreateButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.CreateButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CreateButton.ForeColor = System.Drawing.Color.White;
            this.CreateButton.Location = new System.Drawing.Point(223, 1);
            this.CreateButton.Margin = new System.Windows.Forms.Padding(0, 0, 10, 0);
            this.CreateButton.Name = "CreateButton";
            this.CreateButton.Size = new System.Drawing.Size(67, 30);
            this.CreateButton.TabIndex = 0;
            this.CreateButton.Text = "Create";
            this.CreateButton.UseVisualStyleBackColor = false;
            this.CreateButton.Click += new System.EventHandler(this.HandleCreateButtonClick);
            this.CreateButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.CreateButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // ExitButton
            // 
            this.ExitButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.ExitButton.AutoSize = true;
            this.ExitButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.ExitButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.ExitButton.FlatAppearance.BorderSize = 0;
            this.ExitButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.ExitButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.ExitButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ExitButton.ForeColor = System.Drawing.Color.White;
            this.ExitButton.Location = new System.Drawing.Point(10, 1);
            this.ExitButton.Margin = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.ExitButton.Name = "ExitButton";
            this.ExitButton.Size = new System.Drawing.Size(45, 30);
            this.ExitButton.TabIndex = 1;
            this.ExitButton.Text = "Exit";
            this.ExitButton.UseVisualStyleBackColor = false;
            this.ExitButton.Click += new System.EventHandler(this.HandleExitButtonClick);
            this.ExitButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.ExitButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // albumsFlowPanel
            // 
            this.albumsFlowPanel.AutoScroll = true;
            this.albumsFlowPanel.BackColor = System.Drawing.Color.White;
            this.albumsFlowPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.albumsFlowPanel.Location = new System.Drawing.Point(10, 39);
            this.albumsFlowPanel.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
            this.albumsFlowPanel.Name = "albumsFlowPanel";
            this.albumsFlowPanel.Size = new System.Drawing.Size(280, 166);
            this.albumsFlowPanel.TabIndex = 2;
            // 
            // DividerPanel
            // 
            this.DividerPanel.BackColor = System.Drawing.Color.Black;
            this.DividerPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DividerPanel.Location = new System.Drawing.Point(10, 35);
            this.DividerPanel.Margin = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.DividerPanel.Name = "DividerPanel";
            this.DividerPanel.Size = new System.Drawing.Size(280, 1);
            this.DividerPanel.TabIndex = 3;
            // 
            // HomeScreenUserControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this.HomeScreenPanel);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "HomeScreenUserControl";
            this.Size = new System.Drawing.Size(300, 244);
            this.HomeScreenPanel.ResumeLayout(false);
            this.HeadingPanel.ResumeLayout(false);
            this.HeadingPanel.PerformLayout();
            this.HomeScreenActionPanel.ResumeLayout(false);
            this.HomeScreenActionPanel.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel HomeScreenPanel;
        private System.Windows.Forms.Panel HeadingPanel;
        private System.Windows.Forms.Label AlbumsLabel;
        private System.Windows.Forms.Panel HomeScreenActionPanel;
        private System.Windows.Forms.Button ExitButton;
        private System.Windows.Forms.Button CreateButton;
        private System.Windows.Forms.FlowLayoutPanel albumsFlowPanel;
        private System.Windows.Forms.Panel DividerPanel;
    }
}
