// <autogenerated />
namespace PhotoBuddy.Screens
{
    partial class CropPhotoControl
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.foundationTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.captionLabel = new System.Windows.Forms.Label();
            this.footerTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.rightFooterPanel = new System.Windows.Forms.Panel();
            this.RightButton = new System.Windows.Forms.Button();
            this.footerLabel = new System.Windows.Forms.Label();
            this.leftFooterPanel = new System.Windows.Forms.Panel();
            this.LeftButton = new System.Windows.Forms.Button();
            this.photoCropBox = new PhotoBuddy.Controls.CropBox();
            this.foundationTableLayoutPanel.SuspendLayout();
            this.footerTableLayoutPanel.SuspendLayout();
            this.rightFooterPanel.SuspendLayout();
            this.leftFooterPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.photoCropBox)).BeginInit();
            this.SuspendLayout();
            // 
            // foundationTableLayoutPanel
            // 
            this.foundationTableLayoutPanel.BackColor = System.Drawing.Color.White;
            this.foundationTableLayoutPanel.ColumnCount = 1;
            this.foundationTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.foundationTableLayoutPanel.Controls.Add(this.captionLabel, 0, 1);
            this.foundationTableLayoutPanel.Controls.Add(this.footerTableLayoutPanel, 0, 2);
            this.foundationTableLayoutPanel.Controls.Add(this.photoCropBox, 0, 0);
            this.foundationTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.foundationTableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.foundationTableLayoutPanel.Margin = new System.Windows.Forms.Padding(2);
            this.foundationTableLayoutPanel.Name = "foundationTableLayoutPanel";
            this.foundationTableLayoutPanel.RowCount = 3;
            this.foundationTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.foundationTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 46F));
            this.foundationTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.foundationTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.foundationTableLayoutPanel.Size = new System.Drawing.Size(586, 462);
            this.foundationTableLayoutPanel.TabIndex = 2;
            // 
            // captionLabel
            // 
            this.captionLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.captionLabel.AutoSize = true;
            this.captionLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.captionLabel.ForeColor = System.Drawing.Color.Black;
            this.captionLabel.Location = new System.Drawing.Point(0, 388);
            this.captionLabel.Margin = new System.Windows.Forms.Padding(0);
            this.captionLabel.Name = "captionLabel";
            this.captionLabel.Size = new System.Drawing.Size(586, 29);
            this.captionLabel.TabIndex = 9;
            this.captionLabel.Text = "captionLabel";
            this.captionLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // footerTableLayoutPanel
            // 
            this.footerTableLayoutPanel.BackColor = System.Drawing.Color.WhiteSmoke;
            this.footerTableLayoutPanel.ColumnCount = 5;
            this.footerTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.footerTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.footerTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 100F));
            this.footerTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.footerTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.footerTableLayoutPanel.Controls.Add(this.rightFooterPanel, 4, 0);
            this.footerTableLayoutPanel.Controls.Add(this.leftFooterPanel, 0, 0);
            this.footerTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.footerTableLayoutPanel.Location = new System.Drawing.Point(0, 426);
            this.footerTableLayoutPanel.Margin = new System.Windows.Forms.Padding(0);
            this.footerTableLayoutPanel.Name = "footerTableLayoutPanel";
            this.footerTableLayoutPanel.RowCount = 1;
            this.footerTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.footerTableLayoutPanel.Size = new System.Drawing.Size(586, 36);
            this.footerTableLayoutPanel.TabIndex = 3;
            // 
            // rightFooterPanel
            // 
            this.rightFooterPanel.Controls.Add(this.RightButton);
            this.rightFooterPanel.Controls.Add(this.footerLabel);
            this.rightFooterPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rightFooterPanel.Location = new System.Drawing.Point(383, 0);
            this.rightFooterPanel.Margin = new System.Windows.Forms.Padding(0);
            this.rightFooterPanel.Name = "rightFooterPanel";
            this.rightFooterPanel.Size = new System.Drawing.Size(203, 36);
            this.rightFooterPanel.TabIndex = 5;
            // 
            // RightButton
            // 
            this.RightButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.RightButton.AutoSize = true;
            this.RightButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.RightButton.BackColor = System.Drawing.Color.Transparent;
            this.RightButton.FlatAppearance.BorderSize = 0;
            this.RightButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.RightButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.RightButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RightButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.RightButton.Location = new System.Drawing.Point(88, 4);
            this.RightButton.Margin = new System.Windows.Forms.Padding(0, 0, 10, 0);
            this.RightButton.Name = "RightButton";
            this.RightButton.Size = new System.Drawing.Size(105, 30);
            this.RightButton.TabIndex = 11;
            this.RightButton.Text = "RightButton";
            this.RightButton.UseVisualStyleBackColor = false;
            this.RightButton.Visible = false;
            // 
            // footerLabel
            // 
            this.footerLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.footerLabel.AutoSize = true;
            this.footerLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.footerLabel.Location = new System.Drawing.Point(38, 14);
            this.footerLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.footerLabel.Name = "footerLabel";
            this.footerLabel.Size = new System.Drawing.Size(30, 13);
            this.footerLabel.TabIndex = 4;
            this.footerLabel.Text = "1/32";
            this.footerLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // leftFooterPanel
            // 
            this.leftFooterPanel.Controls.Add(this.LeftButton);
            this.leftFooterPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.leftFooterPanel.Location = new System.Drawing.Point(0, 0);
            this.leftFooterPanel.Margin = new System.Windows.Forms.Padding(0);
            this.leftFooterPanel.Name = "leftFooterPanel";
            this.leftFooterPanel.Size = new System.Drawing.Size(203, 36);
            this.leftFooterPanel.TabIndex = 6;
            // 
            // LeftButton
            // 
            this.LeftButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.LeftButton.AutoSize = true;
            this.LeftButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.LeftButton.BackColor = System.Drawing.Color.Transparent;
            this.LeftButton.FlatAppearance.BorderSize = 0;
            this.LeftButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.LeftButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.LeftButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LeftButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.LeftButton.Location = new System.Drawing.Point(10, 4);
            this.LeftButton.Margin = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.LeftButton.Name = "LeftButton";
            this.LeftButton.Size = new System.Drawing.Size(95, 30);
            this.LeftButton.TabIndex = 1;
            this.LeftButton.Text = "LeftButton";
            this.LeftButton.UseMnemonic = false;
            this.LeftButton.UseVisualStyleBackColor = false;
            // 
            // photoCropBox
            // 
            this.photoCropBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.photoCropBox.Location = new System.Drawing.Point(3, 3);
            this.photoCropBox.Name = "photoCropBox";
            this.photoCropBox.Photo = null;
            this.photoCropBox.Size = new System.Drawing.Size(580, 374);
            this.photoCropBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.photoCropBox.TabIndex = 10;
            this.photoCropBox.TabStop = false;
            // 
            // CropPhotoControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.foundationTableLayoutPanel);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "CropPhotoControl";
            this.Size = new System.Drawing.Size(586, 462);
            this.foundationTableLayoutPanel.ResumeLayout(false);
            this.foundationTableLayoutPanel.PerformLayout();
            this.footerTableLayoutPanel.ResumeLayout(false);
            this.rightFooterPanel.ResumeLayout(false);
            this.rightFooterPanel.PerformLayout();
            this.leftFooterPanel.ResumeLayout(false);
            this.leftFooterPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.photoCropBox)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel foundationTableLayoutPanel;
        private System.Windows.Forms.Label footerLabel;
        private System.Windows.Forms.Label captionLabel;
        private System.Windows.Forms.TableLayoutPanel footerTableLayoutPanel;
        private System.Windows.Forms.Panel rightFooterPanel;
        private System.Windows.Forms.Panel leftFooterPanel;
        public System.Windows.Forms.Button LeftButton;
        public Controls.CropBox photoCropBox;
        public System.Windows.Forms.Button RightButton;
    }
}
