// <autogenerated />
namespace PhotoBuddy.Controls
{
    partial class AlbumThumbnailUserControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AlbumThumbnailUserControl));
            this.primarySplitContainer = new System.Windows.Forms.SplitContainer();
            this.coverImagePictureBox = new System.Windows.Forms.PictureBox();
            this.contextMenuStrip1 = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.deleteToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.AlbumCountLabel = new System.Windows.Forms.Label();
            this.AlbumNameLabel = new System.Windows.Forms.Label();
            this.renameToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            ((System.ComponentModel.ISupportInitialize)(this.primarySplitContainer)).BeginInit();
            this.primarySplitContainer.Panel1.SuspendLayout();
            this.primarySplitContainer.Panel2.SuspendLayout();
            this.primarySplitContainer.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.coverImagePictureBox)).BeginInit();
            this.contextMenuStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // primarySplitContainer
            // 
            this.primarySplitContainer.BackColor = System.Drawing.SystemColors.Window;
            this.primarySplitContainer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.primarySplitContainer.FixedPanel = System.Windows.Forms.FixedPanel.Panel2;
            this.primarySplitContainer.IsSplitterFixed = true;
            this.primarySplitContainer.Location = new System.Drawing.Point(0, 0);
            this.primarySplitContainer.Name = "primarySplitContainer";
            this.primarySplitContainer.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // primarySplitContainer.Panel1
            // 
            this.primarySplitContainer.Panel1.BackColor = System.Drawing.SystemColors.Window;
            this.primarySplitContainer.Panel1.Controls.Add(this.AlbumCountLabel);
            this.primarySplitContainer.Panel1.Controls.Add(this.coverImagePictureBox);
            // 
            // primarySplitContainer.Panel2
            // 
            this.primarySplitContainer.Panel2.Controls.Add(this.AlbumNameLabel);
            this.primarySplitContainer.Panel2MinSize = 13;
            this.primarySplitContainer.Size = new System.Drawing.Size(150, 150);
            this.primarySplitContainer.SplitterDistance = 121;
            this.primarySplitContainer.TabIndex = 0;
            // 
            // coverImagePictureBox
            // 
            this.coverImagePictureBox.ContextMenuStrip = this.contextMenuStrip1;
            this.coverImagePictureBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.coverImagePictureBox.Image = ((System.Drawing.Image)(resources.GetObject("coverImagePictureBox.Image")));
            this.coverImagePictureBox.Location = new System.Drawing.Point(0, 0);
            this.coverImagePictureBox.Name = "coverImagePictureBox";
            this.coverImagePictureBox.Size = new System.Drawing.Size(150, 121);
            this.coverImagePictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.coverImagePictureBox.TabIndex = 0;
            this.coverImagePictureBox.TabStop = false;
            this.coverImagePictureBox.Click += new System.EventHandler(this.HandleCoverImagePictureBoxClick);
            // 
            // contextMenuStrip1
            // 
            this.contextMenuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.deleteToolStripMenuItem,
            this.renameToolStripMenuItem});
            this.contextMenuStrip1.Name = "contextMenuStrip1";
            this.contextMenuStrip1.Size = new System.Drawing.Size(153, 70);
            // 
            // deleteToolStripMenuItem
            // 
            this.deleteToolStripMenuItem.Name = "deleteToolStripMenuItem";
            this.deleteToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.deleteToolStripMenuItem.Text = "Delete";
            this.deleteToolStripMenuItem.Click += new System.EventHandler(this.HandleDeleteToolStripItemClick);
            // 
            // AlbumCountLabel
            // 
            this.AlbumCountLabel.AutoSize = true;
            this.AlbumCountLabel.Font = new System.Drawing.Font("Magneto", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AlbumCountLabel.ForeColor = System.Drawing.SystemColors.ActiveCaption;
            this.AlbumCountLabel.Location = new System.Drawing.Point(92, 0);
            this.AlbumCountLabel.Name = "AlbumCountLabel";
            this.AlbumCountLabel.Size = new System.Drawing.Size(55, 24);
            this.AlbumCountLabel.TabIndex = 1;
            this.AlbumCountLabel.Text = "000";
            this.AlbumCountLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // AlbumNameLabel
            // 
            this.AlbumNameLabel.AutoEllipsis = true;
            this.AlbumNameLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.AlbumNameLabel.Location = new System.Drawing.Point(0, 0);
            this.AlbumNameLabel.MaximumSize = new System.Drawing.Size(125, 0);
            this.AlbumNameLabel.Name = "AlbumNameLabel";
            this.AlbumNameLabel.Size = new System.Drawing.Size(125, 25);
            this.AlbumNameLabel.TabIndex = 1;
            this.AlbumNameLabel.Text = "Name";
            this.AlbumNameLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // renameToolStripMenuItem
            // 
            this.renameToolStripMenuItem.Name = "renameToolStripMenuItem";
            this.renameToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.renameToolStripMenuItem.Text = "Rename";
            this.renameToolStripMenuItem.Click += new System.EventHandler(this.HandleRenameAlbumClick);
            // 
            // AlbumThumbnailUserControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.primarySplitContainer);
            this.Name = "AlbumThumbnailUserControl";
            this.primarySplitContainer.Panel1.ResumeLayout(false);
            this.primarySplitContainer.Panel1.PerformLayout();
            this.primarySplitContainer.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.primarySplitContainer)).EndInit();
            this.primarySplitContainer.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.coverImagePictureBox)).EndInit();
            this.contextMenuStrip1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.SplitContainer primarySplitContainer;
        private System.Windows.Forms.Label AlbumCountLabel;
        private System.Windows.Forms.PictureBox coverImagePictureBox;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip1;
        private System.Windows.Forms.ToolStripMenuItem deleteToolStripMenuItem;
        private System.Windows.Forms.Label AlbumNameLabel;
        private System.Windows.Forms.ToolStripMenuItem renameToolStripMenuItem;

    }
}
