// <autogenerated />
namespace PhotoBuddy.Controls
{
    partial class AlbumThumnailUserControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AlbumThumnailUserControl));
            this.primarySplitContainer = new System.Windows.Forms.SplitContainer();
            this.coverImagePictureBox = new System.Windows.Forms.PictureBox();
            this.contextMenuStrip1 = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.deleteToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.AlbumNameLabel = new System.Windows.Forms.Label();
            this.AlbumCountLabel = new System.Windows.Forms.Label();
            this.staticLabel = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.primarySplitContainer)).BeginInit();
            this.primarySplitContainer.Panel1.SuspendLayout();
            this.primarySplitContainer.Panel2.SuspendLayout();
            this.primarySplitContainer.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.coverImagePictureBox)).BeginInit();
            this.contextMenuStrip1.SuspendLayout();
            this.flowLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // primarySplitContainer
            // 
            this.primarySplitContainer.BackColor = System.Drawing.SystemColors.Window;
            this.primarySplitContainer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.primarySplitContainer.FixedPanel = System.Windows.Forms.FixedPanel.Panel2;
            this.primarySplitContainer.IsSplitterFixed = true;
            this.primarySplitContainer.Location = new System.Drawing.Point(0, 0);
            this.primarySplitContainer.Name = "primarySplitContainer";
            this.primarySplitContainer.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // primarySplitContainer.Panel1
            // 
            this.primarySplitContainer.Panel1.BackColor = System.Drawing.SystemColors.Window;
            this.primarySplitContainer.Panel1.Controls.Add(this.coverImagePictureBox);
            // 
            // primarySplitContainer.Panel2
            // 
            this.primarySplitContainer.Panel2.Controls.Add(this.flowLayoutPanel1);
            this.primarySplitContainer.Panel2MinSize = 13;
            this.primarySplitContainer.Size = new System.Drawing.Size(150, 150);
            this.primarySplitContainer.SplitterDistance = 121;
            this.primarySplitContainer.TabIndex = 0;
            // 
            // coverImagePictureBox
            // 
            this.coverImagePictureBox.ContextMenuStrip = this.contextMenuStrip1;
            this.coverImagePictureBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.coverImagePictureBox.Image = ((System.Drawing.Image)(resources.GetObject("coverImagePictureBox.Image")));
            this.coverImagePictureBox.Location = new System.Drawing.Point(0, 0);
            this.coverImagePictureBox.Name = "coverImagePictureBox";
            this.coverImagePictureBox.Size = new System.Drawing.Size(150, 121);
            this.coverImagePictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.coverImagePictureBox.TabIndex = 0;
            this.coverImagePictureBox.TabStop = false;
            this.coverImagePictureBox.Click += new System.EventHandler(this.HandleCoverImagePictureBoxClick);
            // 
            // contextMenuStrip1
            // 
            this.contextMenuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.deleteToolStripMenuItem});
            this.contextMenuStrip1.Name = "contextMenuStrip1";
            this.contextMenuStrip1.Size = new System.Drawing.Size(153, 48);
            // 
            // deleteToolStripMenuItem
            // 
            this.deleteToolStripMenuItem.Name = "deleteToolStripMenuItem";
            this.deleteToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.deleteToolStripMenuItem.Text = "Delete";
            this.deleteToolStripMenuItem.Click += new System.EventHandler(this.HandleDeleteToolStripItemClick);
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.BackColor = System.Drawing.SystemColors.Window;
            this.flowLayoutPanel1.Controls.Add(this.AlbumNameLabel);
            this.flowLayoutPanel1.Controls.Add(this.AlbumCountLabel);
            this.flowLayoutPanel1.Controls.Add(this.staticLabel);
            this.flowLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(150, 25);
            this.flowLayoutPanel1.TabIndex = 0;
            // 
            // AlbumNameLabel
            // 
            this.AlbumNameLabel.AutoSize = true;
            this.AlbumNameLabel.Location = new System.Drawing.Point(3, 0);
            this.AlbumNameLabel.MaximumSize = new System.Drawing.Size(125, 0);
            this.AlbumNameLabel.Name = "AlbumNameLabel";
            this.AlbumNameLabel.Size = new System.Drawing.Size(35, 13);
            this.AlbumNameLabel.TabIndex = 0;
            this.AlbumNameLabel.Text = "Name";
            // 
            // AlbumCountLabel
            // 
            this.AlbumCountLabel.AutoSize = true;
            this.AlbumCountLabel.Location = new System.Drawing.Point(44, 0);
            this.AlbumCountLabel.Name = "AlbumCountLabel";
            this.AlbumCountLabel.Size = new System.Drawing.Size(13, 13);
            this.AlbumCountLabel.TabIndex = 1;
            this.AlbumCountLabel.Text = "0";
            // 
            // staticLabel
            // 
            this.staticLabel.AutoSize = true;
            this.staticLabel.Location = new System.Drawing.Point(63, 0);
            this.staticLabel.Name = "staticLabel";
            this.staticLabel.Size = new System.Drawing.Size(39, 13);
            this.staticLabel.TabIndex = 2;
            this.staticLabel.Text = "photos";
            // 
            // AlbumThumnailUserControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.primarySplitContainer);
            this.Name = "AlbumThumnailUserControl";
            this.primarySplitContainer.Panel1.ResumeLayout(false);
            this.primarySplitContainer.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.primarySplitContainer)).EndInit();
            this.primarySplitContainer.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.coverImagePictureBox)).EndInit();
            this.contextMenuStrip1.ResumeLayout(false);
            this.flowLayoutPanel1.ResumeLayout(false);
            this.flowLayoutPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.SplitContainer primarySplitContainer;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private System.Windows.Forms.Label AlbumNameLabel;
        private System.Windows.Forms.Label AlbumCountLabel;
        private System.Windows.Forms.PictureBox coverImagePictureBox;
        private System.Windows.Forms.Label staticLabel;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip1;
        private System.Windows.Forms.ToolStripMenuItem deleteToolStripMenuItem;

    }
}
