// <autogenerated />
namespace PhotoBuddy.Controls
{
    partial class AlbumIconUserControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AlbumIconUserControl));
            this.AlbumIconLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.ThumbnailPanel = new System.Windows.Forms.Panel();
            this.AlbumCountLabel = new System.Windows.Forms.Label();
            this.CoverPhotoPictureBox = new System.Windows.Forms.PictureBox();
            this.AlbumContextMenuStrip = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.DeleteToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.RenameToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ThumbnailPictureBox = new System.Windows.Forms.PictureBox();
            this.AlbumNameTextBox = new System.Windows.Forms.TextBox();
            this.AlbumIconLayoutPanel.SuspendLayout();
            this.ThumbnailPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.CoverPhotoPictureBox)).BeginInit();
            this.AlbumContextMenuStrip.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ThumbnailPictureBox)).BeginInit();
            this.SuspendLayout();
            // 
            // AlbumIconLayoutPanel
            // 
            this.AlbumIconLayoutPanel.BackColor = System.Drawing.SystemColors.Window;
            this.AlbumIconLayoutPanel.ColumnCount = 1;
            this.AlbumIconLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.AlbumIconLayoutPanel.Controls.Add(this.ThumbnailPanel, 0, 0);
            this.AlbumIconLayoutPanel.Controls.Add(this.AlbumNameTextBox, 0, 1);
            this.AlbumIconLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.AlbumIconLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.AlbumIconLayoutPanel.Margin = new System.Windows.Forms.Padding(0);
            this.AlbumIconLayoutPanel.Name = "AlbumIconLayoutPanel";
            this.AlbumIconLayoutPanel.RowCount = 2;
            this.AlbumIconLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 124F));
            this.AlbumIconLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 26F));
            this.AlbumIconLayoutPanel.Size = new System.Drawing.Size(164, 150);
            this.AlbumIconLayoutPanel.TabIndex = 1;
            // 
            // ThumbnailPanel
            // 
            this.ThumbnailPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.ThumbnailPanel.AutoSize = true;
            this.ThumbnailPanel.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.ThumbnailPanel.BackColor = System.Drawing.Color.White;
            this.ThumbnailPanel.Controls.Add(this.AlbumCountLabel);
            this.ThumbnailPanel.Controls.Add(this.CoverPhotoPictureBox);
            this.ThumbnailPanel.Controls.Add(this.ThumbnailPictureBox);
            this.ThumbnailPanel.Location = new System.Drawing.Point(0, 0);
            this.ThumbnailPanel.Margin = new System.Windows.Forms.Padding(0);
            this.ThumbnailPanel.MinimumSize = new System.Drawing.Size(10, 10);
            this.ThumbnailPanel.Name = "ThumbnailPanel";
            this.ThumbnailPanel.Padding = new System.Windows.Forms.Padding(2);
            this.ThumbnailPanel.Size = new System.Drawing.Size(164, 124);
            this.ThumbnailPanel.TabIndex = 0;
            // 
            // AlbumCountLabel
            // 
            this.AlbumCountLabel.BackColor = System.Drawing.Color.White;
            this.AlbumCountLabel.Location = new System.Drawing.Point(25, 5);
            this.AlbumCountLabel.Name = "AlbumCountLabel";
            this.AlbumCountLabel.Size = new System.Drawing.Size(48, 14);
            this.AlbumCountLabel.TabIndex = 2;
            this.AlbumCountLabel.Text = "57 ";
            this.AlbumCountLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // CoverPhotoPictureBox
            // 
            this.CoverPhotoPictureBox.BackColor = System.Drawing.Color.Black;
            this.CoverPhotoPictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.CoverPhotoPictureBox.ContextMenuStrip = this.AlbumContextMenuStrip;
            this.CoverPhotoPictureBox.Location = new System.Drawing.Point(37, 31);
            this.CoverPhotoPictureBox.Name = "CoverPhotoPictureBox";
            this.CoverPhotoPictureBox.Size = new System.Drawing.Size(90, 74);
            this.CoverPhotoPictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.CoverPhotoPictureBox.TabIndex = 1;
            this.CoverPhotoPictureBox.TabStop = false;
            this.CoverPhotoPictureBox.Click += new System.EventHandler(this.HandleCoverImagePictureBoxClick);
            this.CoverPhotoPictureBox.MouseEnter += new System.EventHandler(this.HighlightAlbum);
            this.CoverPhotoPictureBox.MouseLeave += new System.EventHandler(this.RemovePhotoHighlight);
            // 
            // AlbumContextMenuStrip
            // 
            this.AlbumContextMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.DeleteToolStripMenuItem,
            this.RenameToolStripMenuItem});
            this.AlbumContextMenuStrip.Name = "albumContextMenuStrip";
            this.AlbumContextMenuStrip.Size = new System.Drawing.Size(118, 48);
            // 
            // DeleteToolStripMenuItem
            // 
            this.DeleteToolStripMenuItem.Name = "DeleteToolStripMenuItem";
            this.DeleteToolStripMenuItem.Size = new System.Drawing.Size(117, 22);
            this.DeleteToolStripMenuItem.Text = "Delete";
            this.DeleteToolStripMenuItem.Click += new System.EventHandler(this.HandleDeleteToolStripItemClick);
            // 
            // RenameToolStripMenuItem
            // 
            this.RenameToolStripMenuItem.Name = "RenameToolStripMenuItem";
            this.RenameToolStripMenuItem.Size = new System.Drawing.Size(117, 22);
            this.RenameToolStripMenuItem.Text = "Rename";
            this.RenameToolStripMenuItem.Click += new System.EventHandler(this.HandleRenameAlbumClick);
            // 
            // ThumbnailPictureBox
            // 
            this.ThumbnailPictureBox.BackColor = System.Drawing.Color.Transparent;
            this.ThumbnailPictureBox.ContextMenuStrip = this.AlbumContextMenuStrip;
            this.ThumbnailPictureBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ThumbnailPictureBox.Image = ((System.Drawing.Image)(resources.GetObject("ThumbnailPictureBox.Image")));
            this.ThumbnailPictureBox.Location = new System.Drawing.Point(2, 2);
            this.ThumbnailPictureBox.Margin = new System.Windows.Forms.Padding(5);
            this.ThumbnailPictureBox.Name = "ThumbnailPictureBox";
            this.ThumbnailPictureBox.Size = new System.Drawing.Size(160, 120);
            this.ThumbnailPictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.ThumbnailPictureBox.TabIndex = 0;
            this.ThumbnailPictureBox.TabStop = false;
            this.ThumbnailPictureBox.Click += new System.EventHandler(this.HandleCoverImagePictureBoxClick);
            this.ThumbnailPictureBox.MouseEnter += new System.EventHandler(this.HighlightAlbum);
            this.ThumbnailPictureBox.MouseLeave += new System.EventHandler(this.RemovePhotoHighlight);
            // 
            // AlbumNameTextBox
            // 
            this.AlbumNameTextBox.BackColor = System.Drawing.SystemColors.Window;
            this.AlbumNameTextBox.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.AlbumNameTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.AlbumNameTextBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AlbumNameTextBox.Location = new System.Drawing.Point(1, 125);
            this.AlbumNameTextBox.Margin = new System.Windows.Forms.Padding(1);
            this.AlbumNameTextBox.Name = "AlbumNameTextBox";
            this.AlbumNameTextBox.ReadOnly = true;
            this.AlbumNameTextBox.Size = new System.Drawing.Size(162, 13);
            this.AlbumNameTextBox.TabIndex = 1;
            this.AlbumNameTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // AlbumIconUserControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.AlbumIconLayoutPanel);
            this.Name = "AlbumIconUserControl";
            this.Size = new System.Drawing.Size(164, 150);
            this.AlbumIconLayoutPanel.ResumeLayout(false);
            this.AlbumIconLayoutPanel.PerformLayout();
            this.ThumbnailPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.CoverPhotoPictureBox)).EndInit();
            this.AlbumContextMenuStrip.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ThumbnailPictureBox)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel AlbumIconLayoutPanel;
        private System.Windows.Forms.Panel ThumbnailPanel;
        private System.Windows.Forms.PictureBox ThumbnailPictureBox;
        private System.Windows.Forms.TextBox AlbumNameTextBox;
        private System.Windows.Forms.Label AlbumCountLabel;
        private System.Windows.Forms.PictureBox CoverPhotoPictureBox;
        private System.Windows.Forms.ContextMenuStrip AlbumContextMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem DeleteToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem RenameToolStripMenuItem;
    }
}
