// <autogenerated />
namespace PhotoBuddy.Controls
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    /// <summary>
    /// TODO: Update summary.
    /// </summary>
    public partial class CropBox
    {
        /// <summary>
        /// Initializes the component.
        /// </summary>
        private void InitializeComponent()
        {
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            this.SuspendLayout();

            // CropBox
            this.MouseDown += new System.Windows.Forms.MouseEventHandler(this.HandleMouseDown);
            this.MouseMove += new System.Windows.Forms.MouseEventHandler(this.HandleMouseMove);
            this.MouseUp += new System.Windows.Forms.MouseEventHandler(this.HandleMouseUp);
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
            this.ResumeLayout(false);
        }
    }
}
