// <autogenerated />
namespace PhotoBuddy
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.screenHolderPanel = new System.Windows.Forms.Panel();
            this.MainScreenTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.contentPanel = new System.Windows.Forms.Panel();
            this.photoBuddyButton = new System.Windows.Forms.Button();
            this.searchControl = new PhotoBuddy.Controls.SearchControl();
            this.MainScreenTableLayoutPanel.SuspendLayout();
            this.contentPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // screenHolderPanel
            // 
            this.screenHolderPanel.BackColor = System.Drawing.Color.White;
            this.screenHolderPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.screenHolderPanel.Location = new System.Drawing.Point(0, 36);
            this.screenHolderPanel.Margin = new System.Windows.Forms.Padding(0);
            this.screenHolderPanel.Name = "screenHolderPanel";
            this.screenHolderPanel.Size = new System.Drawing.Size(784, 526);
            this.screenHolderPanel.TabIndex = 2;
            // 
            // MainScreenTableLayoutPanel
            // 
            this.MainScreenTableLayoutPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(146)))), ((int)(((byte)(190)))));
            this.MainScreenTableLayoutPanel.ColumnCount = 1;
            this.MainScreenTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainScreenTableLayoutPanel.Controls.Add(this.screenHolderPanel, 0, 1);
            this.MainScreenTableLayoutPanel.Controls.Add(this.contentPanel, 0, 0);
            this.MainScreenTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainScreenTableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.MainScreenTableLayoutPanel.Margin = new System.Windows.Forms.Padding(0);
            this.MainScreenTableLayoutPanel.Name = "MainScreenTableLayoutPanel";
            this.MainScreenTableLayoutPanel.RowCount = 2;
            this.MainScreenTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.MainScreenTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainScreenTableLayoutPanel.Size = new System.Drawing.Size(784, 562);
            this.MainScreenTableLayoutPanel.TabIndex = 3;
            // 
            // contentPanel
            // 
            this.contentPanel.AutoSize = true;
            this.contentPanel.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.contentPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.contentPanel.Controls.Add(this.photoBuddyButton);
            this.contentPanel.Controls.Add(this.searchControl);
            this.contentPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.contentPanel.Location = new System.Drawing.Point(0, 0);
            this.contentPanel.Margin = new System.Windows.Forms.Padding(0);
            this.contentPanel.Name = "contentPanel";
            this.contentPanel.Size = new System.Drawing.Size(784, 36);
            this.contentPanel.TabIndex = 3;
            // 
            // photoBuddyButton
            // 
            this.photoBuddyButton.AutoSize = true;
            this.photoBuddyButton.BackColor = System.Drawing.Color.Transparent;
            this.photoBuddyButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.photoBuddyButton.FlatAppearance.BorderSize = 0;
            this.photoBuddyButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.photoBuddyButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.photoBuddyButton.Font = new System.Drawing.Font("Magneto", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.photoBuddyButton.ForeColor = System.Drawing.Color.LightSlateGray;
            this.photoBuddyButton.Location = new System.Drawing.Point(0, 0);
            this.photoBuddyButton.Margin = new System.Windows.Forms.Padding(0);
            this.photoBuddyButton.Name = "photoBuddyButton";
            this.photoBuddyButton.Size = new System.Drawing.Size(160, 35);
            this.photoBuddyButton.TabIndex = 8;
            this.photoBuddyButton.Text = "Photo Buddy";
            this.photoBuddyButton.UseVisualStyleBackColor = false;
            this.photoBuddyButton.Click += new System.EventHandler(this.ShowHomeView);
            // 
            // searchControl
            // 
            this.searchControl.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.searchControl.AutoSize = true;
            this.searchControl.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.searchControl.Location = new System.Drawing.Point(502, 9);
            this.searchControl.Name = "searchControl";
            this.searchControl.Size = new System.Drawing.Size(272, 24);
            this.searchControl.TabIndex = 9;
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 562);
            this.Controls.Add(this.MainScreenTableLayoutPanel);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "HomeScreenForm";
            this.MainScreenTableLayoutPanel.ResumeLayout(false);
            this.MainScreenTableLayoutPanel.PerformLayout();
            this.contentPanel.ResumeLayout(false);
            this.contentPanel.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel screenHolderPanel;
        private System.Windows.Forms.TableLayoutPanel MainScreenTableLayoutPanel;
        private System.Windows.Forms.Panel contentPanel;
        private System.Windows.Forms.Button photoBuddyButton;
        private Controls.SearchControl searchControl;
    }
}