// <autogenerated />
namespace PhotoBuddy
{
    partial class ViewPhotoForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.photoNameLabel = new System.Windows.Forms.Label();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bottomtableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.playPauseButton = new System.Windows.Forms.Button();
            this.previousPhotoButton = new System.Windows.Forms.Button();
            this.panel1 = new System.Windows.Forms.Panel();
            this.RenamePhotoButton = new System.Windows.Forms.Button();
            this.currentAlbumLabel = new System.Windows.Forms.Label();
            this.panel2 = new System.Windows.Forms.Panel();
            this.backButton = new System.Windows.Forms.Button();
            this.nextPhotoButton = new System.Windows.Forms.Button();
            this.tableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.bottomtableLayoutPanel2.SuspendLayout();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.BackColor = System.Drawing.Color.White;
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this.photoNameLabel, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.pictureBox1, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.bottomtableLayoutPanel2, 0, 2);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 3;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 46F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(586, 462);
            this.tableLayoutPanel1.TabIndex = 2;
            // 
            // photoNameLabel
            // 
            this.photoNameLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.photoNameLabel.AutoSize = true;
            this.photoNameLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.photoNameLabel.ForeColor = System.Drawing.Color.Black;
            this.photoNameLabel.Location = new System.Drawing.Point(0, 388);
            this.photoNameLabel.Margin = new System.Windows.Forms.Padding(0);
            this.photoNameLabel.Name = "photoNameLabel";
            this.photoNameLabel.Size = new System.Drawing.Size(586, 29);
            this.photoNameLabel.TabIndex = 9;
            this.photoNameLabel.Text = "displayNameLabel";
            this.photoNameLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pictureBox1.Location = new System.Drawing.Point(10, 10);
            this.pictureBox1.Margin = new System.Windows.Forms.Padding(10, 10, 10, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(566, 370);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 2;
            this.pictureBox1.TabStop = false;
            // 
            // bottomtableLayoutPanel2
            // 
            this.bottomtableLayoutPanel2.BackColor = System.Drawing.Color.WhiteSmoke;
            this.bottomtableLayoutPanel2.ColumnCount = 5;
            this.bottomtableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.bottomtableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.bottomtableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 100F));
            this.bottomtableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.bottomtableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.bottomtableLayoutPanel2.Controls.Add(this.playPauseButton, 2, 0);
            this.bottomtableLayoutPanel2.Controls.Add(this.previousPhotoButton, 1, 0);
            this.bottomtableLayoutPanel2.Controls.Add(this.panel1, 4, 0);
            this.bottomtableLayoutPanel2.Controls.Add(this.panel2, 0, 0);
            this.bottomtableLayoutPanel2.Controls.Add(this.nextPhotoButton, 3, 0);
            this.bottomtableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bottomtableLayoutPanel2.Location = new System.Drawing.Point(0, 426);
            this.bottomtableLayoutPanel2.Margin = new System.Windows.Forms.Padding(0);
            this.bottomtableLayoutPanel2.Name = "bottomtableLayoutPanel2";
            this.bottomtableLayoutPanel2.RowCount = 1;
            this.bottomtableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.bottomtableLayoutPanel2.Size = new System.Drawing.Size(586, 36);
            this.bottomtableLayoutPanel2.TabIndex = 3;
            // 
            // playPauseButton
            // 
            this.playPauseButton.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.playPauseButton.AutoSize = true;
            this.playPauseButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.playPauseButton.BackColor = System.Drawing.Color.Transparent;
            this.playPauseButton.FlatAppearance.BorderSize = 0;
            this.playPauseButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.playPauseButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.playPauseButton.Font = new System.Drawing.Font("Webdings", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.playPauseButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.playPauseButton.Location = new System.Drawing.Point(251, 2);
            this.playPauseButton.Margin = new System.Windows.Forms.Padding(0);
            this.playPauseButton.Name = "playPauseButton";
            this.playPauseButton.Size = new System.Drawing.Size(83, 34);
            this.playPauseButton.TabIndex = 7;
            this.playPauseButton.Text = "4|;";
            this.playPauseButton.UseVisualStyleBackColor = false;
            this.playPauseButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.playPauseButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // previousPhotoButton
            // 
            this.previousPhotoButton.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.previousPhotoButton.AutoSize = true;
            this.previousPhotoButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.previousPhotoButton.BackColor = System.Drawing.Color.Transparent;
            this.previousPhotoButton.FlatAppearance.BorderSize = 0;
            this.previousPhotoButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.previousPhotoButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.previousPhotoButton.Font = new System.Drawing.Font("Webdings", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.previousPhotoButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.previousPhotoButton.Location = new System.Drawing.Point(203, 2);
            this.previousPhotoButton.Margin = new System.Windows.Forms.Padding(0);
            this.previousPhotoButton.Name = "previousPhotoButton";
            this.previousPhotoButton.Size = new System.Drawing.Size(40, 34);
            this.previousPhotoButton.TabIndex = 2;
            this.previousPhotoButton.Text = "9";
            this.previousPhotoButton.UseVisualStyleBackColor = false;
            this.previousPhotoButton.Click += new System.EventHandler(this.HandlePreviousPhotoButtonClick);
            this.previousPhotoButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.previousPhotoButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.RenamePhotoButton);
            this.panel1.Controls.Add(this.currentAlbumLabel);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(383, 0);
            this.panel1.Margin = new System.Windows.Forms.Padding(0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(203, 36);
            this.panel1.TabIndex = 5;
            // 
            // RenamePhotoButton
            // 
            this.RenamePhotoButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.RenamePhotoButton.AutoSize = true;
            this.RenamePhotoButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.RenamePhotoButton.BackColor = System.Drawing.Color.Transparent;
            this.RenamePhotoButton.FlatAppearance.BorderSize = 0;
            this.RenamePhotoButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.RenamePhotoButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.RenamePhotoButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RenamePhotoButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.RenamePhotoButton.Location = new System.Drawing.Point(146, 4);
            this.RenamePhotoButton.Margin = new System.Windows.Forms.Padding(0, 0, 10, 0);
            this.RenamePhotoButton.Name = "RenamePhotoButton";
            this.RenamePhotoButton.Size = new System.Drawing.Size(47, 30);
            this.RenamePhotoButton.TabIndex = 11;
            this.RenamePhotoButton.Text = "Edit";
            this.RenamePhotoButton.UseVisualStyleBackColor = false;
            this.RenamePhotoButton.Click += new System.EventHandler(this.HandleRenamePhotoButtonClick);
            this.RenamePhotoButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.RenamePhotoButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // currentAlbumLabel
            // 
            this.currentAlbumLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.currentAlbumLabel.AutoSize = true;
            this.currentAlbumLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.currentAlbumLabel.Location = new System.Drawing.Point(38, 14);
            this.currentAlbumLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.currentAlbumLabel.Name = "currentAlbumLabel";
            this.currentAlbumLabel.Size = new System.Drawing.Size(30, 13);
            this.currentAlbumLabel.TabIndex = 4;
            this.currentAlbumLabel.Text = "1/32";
            this.currentAlbumLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.backButton);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Margin = new System.Windows.Forms.Padding(0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(203, 36);
            this.panel2.TabIndex = 6;
            // 
            // backButton
            // 
            this.backButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.backButton.AutoSize = true;
            this.backButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.backButton.BackColor = System.Drawing.Color.Transparent;
            this.backButton.FlatAppearance.BorderSize = 0;
            this.backButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.backButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.backButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.backButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.backButton.Location = new System.Drawing.Point(10, 4);
            this.backButton.Margin = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.backButton.Name = "backButton";
            this.backButton.Size = new System.Drawing.Size(59, 30);
            this.backButton.TabIndex = 1;
            this.backButton.Text = "Close";
            this.backButton.UseVisualStyleBackColor = false;
            this.backButton.Click += new System.EventHandler(this.HandleBackButtonClick);
            this.backButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.backButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // nextPhotoButton
            // 
            this.nextPhotoButton.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.nextPhotoButton.AutoSize = true;
            this.nextPhotoButton.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.nextPhotoButton.BackColor = System.Drawing.Color.Transparent;
            this.nextPhotoButton.FlatAppearance.BorderSize = 0;
            this.nextPhotoButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gold;
            this.nextPhotoButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.nextPhotoButton.Font = new System.Drawing.Font("Webdings", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.nextPhotoButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(70)))), ((int)(((byte)(102)))));
            this.nextPhotoButton.Location = new System.Drawing.Point(343, 2);
            this.nextPhotoButton.Margin = new System.Windows.Forms.Padding(0);
            this.nextPhotoButton.Name = "nextPhotoButton";
            this.nextPhotoButton.Size = new System.Drawing.Size(40, 34);
            this.nextPhotoButton.TabIndex = 0;
            this.nextPhotoButton.Text = ":";
            this.nextPhotoButton.UseVisualStyleBackColor = false;
            this.nextPhotoButton.Click += new System.EventHandler(this.HandleNextPhotoButtonClick);
            this.nextPhotoButton.MouseEnter += new System.EventHandler(this.HandleButtonMouseEnter);
            this.nextPhotoButton.MouseLeave += new System.EventHandler(this.HandleButtonMouseLeave);
            // 
            // ViewPhotoForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(586, 462);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "ViewPhotoForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "ViewPhotoForm";
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.bottomtableLayoutPanel2.ResumeLayout(false);
            this.bottomtableLayoutPanel2.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.Label currentAlbumLabel;
        private System.Windows.Forms.Button previousPhotoButton;
        private System.Windows.Forms.Button backButton;
        private System.Windows.Forms.Button nextPhotoButton;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label photoNameLabel;
        private System.Windows.Forms.TableLayoutPanel bottomtableLayoutPanel2;
        private System.Windows.Forms.Button RenamePhotoButton;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Button playPauseButton;
    }
}